In [1]:
import pickle
import pandas as pd

In [2]:
# semantic types sty are parsed from networkx nodes
with open('semanticTypes.pickle', 'rb') as handle:
    sty = pickle.load(handle)

In [3]:
# MRCONSO.RRF is used to link CUI's to their concept names STR
mrconso = pd.read_csv('/Users/qinyilong/Desktop/ScAi/MRCONSO.RRF', sep='|', header=None, dtype=object)
mrconso = mrconso.drop(18, axis=1) # last column is meaningless because the entry ends with '|'
mrconso.columns = ["CUI", "LAT", "TS", "LUI", "STT", "SUI", "ISPREF", "AUI", "SAUI", "SCUI", "SDUI", "SAB", "TTY", "CODE", "STR", "SRL", "SUPPRESS", "CVF"]

In [4]:
# definitions of semantic types srdef are used to link STY's to their TUI's
srdef = pd.read_csv('/Users/qinyilong/Desktop/ScAi/SRDEF', sep='|', header=None, dtype=object)
srdef = srdef.drop(10, axis=1) # last column is meaningless because the entry ends with '|'
srdef.columns = ["RT", "UI", "STYorRL", "STNorRTN", "DEF", "EX", "UN", "NH", "ABR", "RIH"]

In [5]:
# MRSTY.RRF is used to provide categorization of concepts' CUI's to semantic types' TUI's
mrsty = pd.read_csv('/Users/qinyilong/Desktop/ScAi/MRSTY.RRF', sep='|', header=None, dtype=object)
mrsty = mrsty.drop(6, axis=1) # last column is meaningless because the entry ends with '|'
mrsty.columns = ["CUI", "TUI", "STN", "STY", "ATUI", "CVF"]

In [6]:
mrconso

,CUI,LAT,TS,LUI,STT,SUI,ISPREF,AUI,SAUI,SCUI,SDUI,SAB,TTY,CODE,STR,SRL,SUPPRESS,CVF
0,C0000005,ENG,P,L0000005,PF,S0007492,Y,A26634265,NaN,M0019694,D012711,MSH,PEP,D012711,(131)I-Macroaggregated Albumin,0,N,256
1,C0000005,ENG,S,L0270109,PF,S0007491,Y,A26634266,NaN,M0019694,D012711,MSH,ET,D012711,(131)I-MAA,0,N,256
2,C0000005,FRE,P,L6220710,PF,S7133957,Y,A13433185,NaN,M0019694,D012711,MSHFRE,PEP,D012711,Macroagrégats d'albumine marquée à l'iode 131,3,N,NaN
3,C0000005,FRE,S,L6215648,PF,S7133916,Y,A27488794,NaN,M0019694,D012711,MSHFRE,ET,D012711,MAA-I 131,3,N,NaN
4,C0000005,FRE,S,L6215656,PF,S7133956,Y,A27614225,NaN,M0019694,D012711,MSHFRE,ET,D012711,Macroagrégats d'albumine humaine marquée à l'i...,3,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14433445,C4721340,ENG,P,L14979070,PF,S18222043,Y,A29738197,NaN,447562003,NaN,SNOMEDCT_US,XM,447562003,SNOMEDCT_US_2018_09_01 to ICD10_2016 Mappings,9,N,NaN
14433446,C4721341,ENG,P,L14980186,PF,S18222525,Y,A29739672,NaN,NaN,NaN,SRC,VPT,V-MVX2018_08_31,"Manufacturers of Vaccines, 2018_08_31",0,N,NaN
14433447,C4721341,ENG,S,L14980185,PF,S18222524,Y,A29739673,NaN,NaN,NaN,SRC,VAB,V-MVX2018_08_31,MVX2018_08_31,0,N,NaN
14433448,C4721342,ENG,P,L14980190,PF,S18222545,Y,A29739709,NaN,NaN,NaN,SRC,VPT,V-MED-RT_2018_09_04,"Medication Reference Terminology, 2018_09_04",0,N,NaN
14433449,C4721342,ENG,S,L14980191,PF,S18222544,Y,A29739708,NaN,NaN,NaN,SRC,VAB,V-MED-RT_2018_09_04,MED-RT_2018_09_04,0,N,NaN

In [7]:
mrsty

              CUI   TUI  STN  STY ATUI  CVF
0        C0000005  T116  NaN  NaN  NaN  NaN
1        C0000005  T121  NaN  NaN  NaN  NaN
2        C0000005  T130  NaN  NaN  NaN  NaN
3        C0000039  T109  NaN  NaN  NaN  NaN
4        C0000039  T121  NaN  NaN  NaN  NaN
...           ...   ...  ...  ...  ...  ...
4120569  C4721338  T058  NaN  NaN  NaN  NaN
4120570  C4721339  T170  NaN  NaN  NaN  NaN
4120571  C4721340  T170  NaN  NaN  NaN  NaN
4120572  C4721341  T170  NaN  NaN  NaN  NaN
4120573  C4721342  T170  NaN  NaN  NaN  NaN

[4120574 rows x 6 columns]

In [8]:
srdef

,RT,UI,STYorRL,STNorRTN,DEF,EX,UN,NH,ABR,RIH
0,STY,T001,Organism,A1.1,"Generally, a living individual, including all ...",NaN,NaN,NaN,orgm,NaN
1,STY,T002,Plant,A1.1.3.3,"An organism having cellulose cell walls, growi...",NaN,NaN,NaN,plnt,NaN
2,STY,T004,Fungus,A1.1.3.2,A eukaryotic organism characterized by the abs...,NaN,NaN,NaN,fngs,NaN
3,STY,T005,Virus,A1.1.4,An organism consisting of a core of a single n...,NaN,NaN,NaN,virs,NaN
4,STY,T007,Bacterium,A1.1.2,"A small, typically one-celled, prokaryotic mic...",NaN,NaN,NaN,bact,NaN
...,...,...,...,...,...,...,...,...,...,...
176,RL,T189,spatially_related_to,R2,Related by place or region.,NaN,NaN,NaN,SP,spatially_related_to
177,RL,T193,analyzes,R5.3,Studies or examines using established quantita...,NaN,NaN,NaN,AN,analyzed_by
178,RL,T198,branch_of,R1.6,"Arises from the division of. For example, the ...",NaN,NaN,NaN,BR,has_branch
179,RL,T199,tributary_of,R1.7,"Merges with. For example, the confluence of ve...",NaN,NaN,NaN,TB,has_tributary
180,RL,T202,ingredient_of,R1.8,"Is a component of, as in a constituent of a pr...",NaN,NaN,NaN,IG,has_ingredient

In [9]:
sty_to_tui = dict((el, srdef[srdef.STYorRL == el][["UI"]].values[0][0]) for el in sty)

In [10]:
sty_to_cuis = dict((el, []) for el in sty)
for el in sty_to_cuis:
    tui = sty_to_tui[el]
    sty_to_cuis[el] = mrsty[mrsty.TUI == tui].CUI.tolist()

In [11]:
for el in sty_to_cuis:
    print(el)
    print(sty_to_cuis[el])

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [ ]:
with open('STY_to_CUIs.pickle', 'wb') as handle:
    pickle.dump(sty_to_cuis, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [ ]:
sty_to_concepts = sty_to_cuis

In [ ]:
for el in sty_to_concepts:
    for cui in sty_to_concepts[el]:
        print(mrconso[mrconso.CUI == cui].STR)